import{describe,it,expect}from"vitest";import{scanSecretContent}from"@/services/repair-secret-scanner";import{canTransition,assertExecutionTransition}from"@/services/repair-execution-state-machine";import{executionCreateSchema,branchNameSchema}from"@/services/repair-api-schemas";import{assertWorkspaceRoot}from"@/services/repair-workspace";
describe("execution safety blockers",()=>{
it("blocks credential-like content",()=>{for(const s of["ghp_123456789012345678901234567890","-----BEGIN PRIVATE KEY-----\nSECRET\n-----END PRIVATE KEY-----","api_key=abcdefghijklmnopqrstuvwxyz123456","postgres://user:password@db.example.com/app","Bearer abcdefghijklmnopqrstuvwxyz123456","AKIA1234567890ABCDEF"]){expect(scanSecretContent(s).safe).toBe(false)}});
it("allows ordinary source and low-entropy configuration",()=>{expect(scanSecretContent("const token = getToken();\nconst key = 'short';").safe).toBe(true);expect(scanSecretContent("API_TIMEOUT=3000\nPORT=3000").safe).toBe(true)});
it("detects secrets embedded in normal files",()=>{expect(scanSecretContent("export const x='gho_123456789012345678901234567890';").safe).toBe(false)});
it("enforces terminal states",()=>{for(const from of["SUCCEEDED","FAILED","CANCELLED","BLOCKED"])for(const to of["PENDING","AUTHORIZED","RUNNING","TESTING","SUCCEEDED","FAILED","CANCELLED","BLOCKED"])expect(canTransition(from,to)).toBe(false)});
it("allows only intended lifecycle transitions",()=>{expect(canTransition("PENDING","AUTHORIZED")).toBe(true);expect(canTransition("AUTHORIZED","RUNNING")).toBe(true);expect(canTransition("RUNNING","TESTING")).toBe(true);expect(canTransition("TESTING","SUCCEEDED")).toBe(true);expect(canTransition("BLOCKED","SUCCEEDED")).toBe(false);expect(()=>assertExecutionTransition("FAILED","SUCCEEDED")).toThrow()});
it("strictly validates execution and branch input",()=>{expect(executionCreateSchema.safeParse({repairPlanId:"plan_1",authorizedRepositoryId:"repo_1"}).success).toBe(true);expect(executionCreateSchema.safeParse({repairPlanId:"plan",authorizedRepositoryId:"repo",status:"RUNNING"}).success).toBe(false);expect(branchNameSchema.safeParse("repair/abc_123").success).toBe(true);expect(branchNameSchema.safeParse("main").success).toBe(false);expect(branchNameSchema.safeParse("repair/../main").success).toBe(false)});
it("rejects unauthorized workspace roots",()=>{expect(()=>assertWorkspaceRoot("/tmp/aop-repair-other/x")).toThrow()});
});
