import{describe,it,expect,afterEach}from"vitest";
import{runGitHubExecutionReadinessAudit}from"@/services/github-execution-readiness";
const original={...process.env};
afterEach(()=>{process.env={...original}});
describe("GitHub execution readiness audit",()=>{
 it("keeps real execution disabled when unset",()=>{delete process.env.GITHUB_REPAIR_EXECUTION_ENABLED;const a=runGitHubExecutionReadinessAudit();expect(a.featureFlag.enabled).toBe(false);expect(a.featureFlag.liveExecutionActive).toBe(false)});
 it("never exposes sensitive configuration",()=>{process.env.GITHUB_APP_PRIVATE_KEY="SECRET-KEY";process.env.GITHUB_APP_CLIENT_SECRET="SECRET-CLIENT";const s=JSON.stringify(runGitHubExecutionReadinessAudit());expect(s).not.toContain("SECRET-KEY");expect(s).not.toContain("SECRET-CLIENT")});
 it("validates workspace traversal and protected paths",()=>{const a=runGitHubExecutionReadinessAudit();expect(a.checks.workspaceSafety.find(x=>x.key==="TRAVERSAL")?.status).toBe("PASS");expect(a.checks.workspaceSafety.find(x=>x.key==="SECRET_PATH")?.status).toBe("PASS")});
 it("checks command policy without executing commands",()=>{const a=runGitHubExecutionReadinessAudit();expect(a.checks.commandSafety.find(x=>x.key==="npm test")?.status).toBe("PASS");expect(a.checks.commandSafety.find(x=>x.key==="ARBITRARY_SHELL")?.status).toBe("PASS");expect(a.checks.commandSafety.find(x=>x.key==="DEPLOYMENT")?.status).toBe("PASS")});
 it("reports missing configuration as BLOCKED when required safety controls cannot be established",()=>{for(const k of["GITHUB_APP_ID","GITHUB_APP_CLIENT_ID","GITHUB_APP_CLIENT_SECRET","GITHUB_APP_PRIVATE_KEY","GITHUB_APP_SLUG","GITHUB_ALLOWED_REPOSITORIES"])delete process.env[k];const a=runGitHubExecutionReadinessAudit();expect(a.status).toBe("NOT_READY");expect(a.warnings.length).toBeGreaterThan(0)});
 it("blocks invalid private-key configuration without exposing the value",()=>{process.env.GITHUB_APP_PRIVATE_KEY="not-a-private-key";const a=runGitHubExecutionReadinessAudit();expect(a.checks.githubConfiguration.find(x=>x.key==="GITHUB_APP_PRIVATE_KEY")?.status).toBe("BLOCKED")});
 it("blocks malformed repository allowlists",()=>{process.env.GITHUB_ALLOWED_REPOSITORIES="not-a-repository";const a=runGitHubExecutionReadinessAudit();expect(a.checks.githubConfiguration.find(x=>x.key==="GITHUB_ALLOWED_REPOSITORIES")?.status).toBe("BLOCKED")});
 it("accepts localhost and HTTPS callback policies only",()=>{process.env.GITHUB_APP_CALLBACK_URL="http://localhost:3000/callback";expect(runGitHubExecutionReadinessAudit().checks.githubConfiguration.find(x=>x.key==="GITHUB_APP_CALLBACK_URL")?.status).toBe("PASS");process.env.GITHUB_APP_CALLBACK_URL="http://example.com/callback";expect(runGitHubExecutionReadinessAudit().checks.githubConfiguration.find(x=>x.key==="GITHUB_APP_CALLBACK_URL")?.status).toBe("BLOCKED")});
 it("reports implementation readiness separately from the live flag",()=>{process.env.GITHUB_REPAIR_EXECUTION_ENABLED="false";const a=runGitHubExecutionReadinessAudit();expect(a.featureFlag.enabled).toBe(false);expect(a.featureFlag.liveExecutionActive).toBe(false);expect(a.realVerificationStatus).toBe("NOT_PERFORMED")});it("keeps configuration, manual verification, and real verification states distinct",()=>{const a=runGitHubExecutionReadinessAudit();expect(a.configurationReadiness).toBe("NOT_READY");expect(a.manualVerificationReadiness).toBe("NOT_READY");expect(a.realVerificationStatus).toBe("NOT_PERFORMED");expect(a.status).toBe("NOT_READY")});
 it("verifies deterministic AI secret-context protection",()=>{const a=runGitHubExecutionReadinessAudit();expect(a.checks.credentialSafety.find(x=>x.key==="AI_EXPOSURE")?.status).toBe("PASS")});
 it("verifies centralized state-transition enforcement",()=>{const a=runGitHubExecutionReadinessAudit();expect(a.checks.stateMachine.find(x=>x.key==="TRANSITION_GUARD")?.status).toBe("PASS");expect(a.checks.stateMachine.find(x=>x.key==="BLOCKED_TERMINAL")?.status).toBe("PASS")});
 it("re-audits the previous safety blockers as resolved",()=>{const a=runGitHubExecutionReadinessAudit();expect(a.blockers).toEqual([]);expect(a.checks.credentialSafety.find(x=>x.key==="AI_EXPOSURE")?.status).toBe("PASS");expect(a.checks.stateMachine.find(x=>x.key==="TRANSITION_GUARD")?.status).toBe("PASS");expect(a.checks.apiSecurity.find(x=>x.key==="INPUT_VALIDATION")?.status).toBe("PASS");expect(a.checks.workspaceSafety.find(x=>x.key==="CLEANUP_ROOT_GUARD")?.status).toBe("PASS")});
it("does not execute GitHub writes",()=>{const a=runGitHubExecutionReadinessAudit();expect(a.checks.deploymentSafety.find(x=>x.key==="AUDIT_SIDE_EFFECT_FREE")?.status).toBe("PASS")});
});