import { z } from "zod";
import dns from "node:dns/promises";
import net from "node:net";
export const targetTypes=["WEBSITE","WEB_APP","API"] as const;
export const diagnosisTargetInputSchema=z.object({url:z.string().trim().min(1).max(2048),targetType:z.enum(targetTypes),displayName:z.string().trim().max(120).optional(),healthEndpoint:z.string().trim().max(512).optional(),apiEndpoint:z.string().trim().max(512).optional(),enabled:z.boolean().optional()});
export type DiagnosisTargetInput=z.infer<typeof diagnosisTargetInputSchema>;
function privateIp(a:string){if(net.isIPv4(a)){const p=a.split(".").map(Number);return p[0]===10||p[0]===127||p[0]===0||p[0]>=224||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||(p[0]===192&&p[1]===0)||(p[0]===198&&(p[1]===18||p[1]===19||(p[1]===51&&p[2]===100))||(p[0]===203&&p[1]===0&&p[2]===113)}const h=a.toLowerCase();return h==="::1"||h==="::"||h.startsWith("::ffff:")||h.startsWith("fc")||h.startsWith("fd")||h.startsWith("fe80")||h.startsWith("ff")||h.startsWith("2001:db8:")}
async function assertPublicHostname(h:string){const x=h.toLowerCase();if(x==="localhost"||x.endsWith(".localhost")||x.endsWith(".local")||x.endsWith(".internal")||x.endsWith(".home")||x.endsWith(".lan"))throw new Error("Local or internal targets are not allowed.");if(net.isIP(h)){if(privateIp(h))throw new Error("Private or local targets are not allowed.");return}const r=await dns.lookup(h,{all:true,verbatim:true});if(!r.length||r.some(x=>privateIp(x.address)))throw new Error("Target resolves to a private or local network address.")}
function endpoint(raw:string|undefined,base:URL){if(!raw)return null;const u=new URL(raw,base);if(u.protocol!==base.protocol||u.origin!==base.origin)throw new Error("Diagnostic endpoints must remain on the target origin.");u.username="";u.password="";u.hash="";return u.toString()}
export async function validateDiagnosisTarget(input:DiagnosisTargetInput){const u=new URL(input.url);if(!["http:","https:"].includes(u.protocol))throw new Error("Only HTTP and HTTPS targets are allowed.");if(u.username||u.password)throw new Error("Embedded credentials are not allowed.");u.hash="";u.hostname=u.hostname.toLowerCase();await assertPublicHostname(u.hostname);return {targetType:input.targetType,displayName:input.displayName?.trim()||null,normalizedUrl:u.toString(),hostname:u.hostname,protocol:u.protocol.replace(":",""),healthEndpoint:endpoint(input.healthEndpoint,u),apiEndpoint:endpoint(input.apiEndpoint,u),enabled:input.enabled??true}}
export async function assertSafeDiagnosticUrl(raw:string,origin:string){const u=new URL(raw),b=new URL(origin);if(u.protocol!==b.protocol||u.origin!==b.origin)throw new Error("Diagnostic request escaped the validated target origin.");if(u.username||u.password)throw new Error("Credentials are not allowed in diagnostic URLs.");await assertPublicHostname(u.hostname);return u}