import "server-only";
import {z} from "zod";
export const githubIssuesConfigSchema=z.object({owner:z.string().trim().regex(/^[A-Za-z0-9](?:[A-Za-z0-9-]{0,37})$/),repo:z.string().trim().regex(/^[A-Za-z0-9._-]{1,100}$/),state:z.enum(["open","closed","all"]).default("open"),labels:z.array(z.string().trim().min(1).max(100)).max(20).default([]),limit:z.number().int().min(1).max(100).default(20),lookbackDays:z.number().int().min(0).max(3650).optional()}).strict();
export type GitHubIssuesConfig=z.infer<typeof githubIssuesConfigSchema>;
export type GitHubIssue={id:number;number:number;title:string;body:string|null;html_url:string;state:string;created_at:string;updated_at:string;labels:Array<{name?:string}>;user?:{login?:string|null;type?:string|null}|null;repository_url?:string};
export type NormalizedGitHubIssue={externalId:string;title:string;summary:string;issueNumber:number;owner:string;repo:string;reference:string;authorLogin?:string;labels:string[];state:string;createdAt:Date;updatedAt:Date;sourceType:"github";signalType:string;problemCategory:string;severity:number;urgency:number;confidence:number;solutionFit:number;businessValueHypothesis:number};
const header={"Accept":"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};
function endpoint(c:GitHubIssuesConfig){const qs=new URLSearchParams({state:c.state,per_page:String(Math.min(c.limit,100)),sort:"updated",direction:"desc"});if(c.labels.length)qs.set("labels",c.labels.join(","));return `https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/issues?${qs}`;}
async function request(url:string,timeoutMs=8000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const res=await fetch(url,{headers:header,signal:controller.signal,cache:"no-store"});if(!res.ok){const retry=res.headers.get("retry-after");const error=res.status===403||res.status===429?"GitHub API rate limit reached.":`GitHub API request failed (HTTP ${res.status}).`;return {ok:false as const,status:res.status,retryAfter:retry,error};}let data:unknown;try{data=await res.json();}catch{return {ok:false as const,status:200,error:"GitHub returned malformed JSON."};}return {ok:true as const,status:res.status,data};}catch(e){return {ok:false as const,status:0,error:e instanceof Error&&e.name==="AbortError"?"GitHub API request timed out.":"Unable to reach GitHub API."};}finally{clearTimeout(timer);}}
export async function validateGitHubIssuesConfig(input:unknown){return githubIssuesConfigSchema.safeParse(input);}
export function classifyGitHubIssue(i:Pick<GitHubIssue,"title"|"body"|"labels">){const text=`${i.title} ${i.body??""} ${i.labels.map(x=>x.name??"").join(" ")}`.toLowerCase();if(/security|vulnerab|cve|exploit|auth|permission/.test(text))return {signalType:"product_failure",problemCategory:"security",severity:90,urgency:90};if(/payment|billing|invoice|checkout|refund|subscription/.test(text))return {signalType:"user_complaint",problemCategory:"payments",severity:82,urgency:82};if(/performance|slow|latency|memory leak|cpu|timeout|crash|hang/.test(text))return {signalType:"product_failure",problemCategory:/infrastructure|server|deploy|database|network/.test(text)?"infrastructure":"technical",severity:78,urgency:75};if(/feature request|feature|enhancement|request/.test(text))return {signalType:"problem_report",problemCategory:"product",severity:62,urgency:55};if(/workflow|developer experience|dx|developer workflow|productivity|automation/.test(text))return {signalType:"problem_report",problemCategory:"workflow",severity:68,urgency:60};if(/bug|error|fail|broken|issue|regression/.test(text))return {signalType:"product_failure",problemCategory:"technical",severity:75,urgency:70};return {signalType:"problem_report",problemCategory:"other",severity:55,urgency:50};}
export function normalizeGitHubIssue(i:GitHubIssue,c:GitHubIssuesConfig):NormalizedGitHubIssue|null{if(!Number.isInteger(i.number)||i.number<1||!i.title||!i.html_url||!i.created_at||!i.updated_at)return null;const cls=classifyGitHubIssue(i);return {externalId:`${c.owner}/${c.repo}#${i.number}`,title:i.title.trim(),summary:(i.body??i.title).trim().slice(0,2000),issueNumber:i.number,owner:c.owner,repo:c.repo,reference:i.html_url,authorLogin:i.user?.login??undefined,labels:i.labels.map(x=>x.name??"").filter(Boolean).slice(0,20),state:i.state,createdAt:new Date(i.created_at),updatedAt:new Date(i.updated_at),sourceType:"github",...cls,confidence:85,solutionFit:60,businessValueHypothesis:65};}
export async function fetchGitHubIssues(config:GitHubIssuesConfig){const parsed=githubIssuesConfigSchema.safeParse(config);if(!parsed.success)return {ok:false as const,error:"Invalid GitHub Issues configuration."};const r=await request(endpoint(parsed.data));if(!r.ok)return {ok:false as const,error:r.error,status:r.status,retryAfter:r.retryAfter};if(!Array.isArray(r.data))return {ok:false as const,error:"GitHub returned an unexpected issues response.",status:r.status};const normalized=r.data.filter((x):x is GitHubIssue=>!!x&&typeof x==="object").map(x=>normalizeGitHubIssue(x,parsed.data)).filter((x):x is NormalizedGitHubIssue=>!!x).slice(0,parsed.data.limit);return {ok:true as const,issues:normalized,rawCount:r.data.length};}
export async function githubHealthCheck(config:unknown){const parsed=githubIssuesConfigSchema.safeParse(config);if(!parsed.success)return {ok:false as const,error:"Invalid GitHub source configuration."};const c=parsed.data;const url=`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}`;const r=await request(url);return r.ok?{ok:true as const}:{ok:false as const,error:r.error};}
export function githubIssuesEndpointForTest(config:GitHubIssuesConfig){return endpoint(config);}
