import "server-only";
import { createPrivateKey } from "node:crypto";
import { z } from "zod";
import { safeWorkspacePath, validateCommand, executionStatusSchema } from "@/services/repair-execution-domain";
import { validateAuthorizationState, createAuthorizationState } from "@/services/github-authorization-state";
import { inspectChangedFile, decideReview } from "@/services/repair-review-domain";
import { scanSecretContent } from "@/services/repair-secret-scanner";
import { canTransition } from "@/services/repair-execution-state-machine";
import { executionCreateSchema, branchNameSchema } from "@/services/repair-api-schemas";
import { assertWorkspaceRoot } from "@/services/repair-workspace";

export const readinessStatusSchema=z.enum(["READY","READY_WITH_WARNINGS","NOT_READY","BLOCKED"]);
export type ReadinessStatus=z.infer<typeof readinessStatusSchema>;
export type ReadinessCheck={key:string;status:"PASS"|"WARNING"|"BLOCKED"|"NOT_CONFIGURED";summary:string;remediation?:string};
export type ReadinessAudit={status:ReadinessStatus;score:number;auditedAt:string;featureFlag:{configured:boolean;enabled:boolean;liveExecutionActive:boolean};controlledVerification:{configured:boolean;enabled:boolean;repositoryConfigured:boolean;executed:boolean;status:"NOT_EXECUTED"|"SUCCEEDED"|"FAILED"};checks:Record<string,ReadinessCheck[]>;blockers:string[];warnings:string[];recommendations:string[]};

const configured=(name:string)=>Boolean(process.env[name]?.trim());
const check=(key:string,status:ReadinessCheck["status"],summary:string,remediation?:string):ReadinessCheck=>({key,status,summary,...(remediation?{remediation}:{})});
const repos=()=> (process.env.GITHUB_ALLOWED_REPOSITORIES??"").split(",").map(x=>x.trim()).filter(Boolean);
const validRepo=(value:string)=>/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(value);

function callbackStatus(value:string|undefined){if(!value)return"NOT_CONFIGURED" as const;try{const u=new URL(value);return u.protocol==="https:"||u.protocol==="http:"&&(u.hostname==="localhost"||u.hostname==="127.0.0.1")?"PASS" as const:"BLOCKED" as const}catch{return"BLOCKED" as const}}
function privateKeyStatus(value:string|undefined){if(!value?.trim())return"NOT_CONFIGURED" as const;try{createPrivateKey(value.replace(/\\n/g,"\n"));return"PASS" as const}catch{return"BLOCKED" as const}}

function configChecks(){const out:ReadinessCheck[]=[];
for(const name of["GITHUB_APP_ID","GITHUB_APP_CLIENT_ID","GITHUB_APP_CLIENT_SECRET","GITHUB_APP_SLUG"]){const ok=configured(name);out.push(check(name,ok?"PASS":"NOT_CONFIGURED",ok?"Configured (value hidden).":"Not configured.","Configure the server-side GitHub App setting before a controlled live test."))}
const pk=privateKeyStatus(process.env.GITHUB_APP_PRIVATE_KEY);out.push(check("GITHUB_APP_PRIVATE_KEY",pk,pk==="PASS"?"Present and parseable; key value is never returned.":pk==="NOT_CONFIGURED"?"Not configured.":"Configured but the private key format is invalid.","Provide a valid server-side GitHub App private key without exposing it to clients or logs."));
const cb=callbackStatus(process.env.GITHUB_APP_CALLBACK_URL);out.push(check("GITHUB_APP_CALLBACK_URL",cb,cb==="PASS"?"Callback URL is HTTPS or localhost-safe.":cb==="NOT_CONFIGURED"?"Callback URL is missing.":"Callback URL is unsafe or invalid.","Use HTTPS in deployed environments or localhost for development."));
const allow=repos(),bad=allow.filter(x=>!validRepo(x)),s=allow.length===0?"NOT_CONFIGURED":bad.length?"BLOCKED":"PASS";out.push(check("GITHUB_ALLOWED_REPOSITORIES",s,s==="PASS"?"Repository allowlist is present and well-formed.":s==="NOT_CONFIGURED"?"Repository allowlist is empty.":"Repository allowlist contains malformed identifiers.","Keep an explicit owner/repository allowlist."));return out}
function controlledVerificationChecks(){const enabled=process.env.GITHUB_CONTROLLED_VERIFICATION_ENABLED==="true",repo=Boolean(process.env.GITHUB_CONTROLLED_VERIFICATION_REPOSITORY?.trim());return[check("CONTROLLED_VERIFICATION_FLAG",enabled?"WARNING":"PASS",enabled?"Controlled verification is explicitly enabled in this environment.":"Controlled verification is disabled by default."),check("CONTROLLED_VERIFICATION_REPOSITORY",repo?"PASS":"NOT_CONFIGURED",repo?"A server-side verification repository is configured; its value is hidden.":"No server-side verification repository is configured.")]}
function featureFlagChecks(){const enabled=process.env.GITHUB_REPAIR_EXECUTION_ENABLED==="true";return[check("DEFAULT_DISABLED",enabled?"WARNING":"PASS",enabled?"Real execution is explicitly enabled in this environment.":"Real execution remains disabled by default.","Keep GITHUB_REPAIR_EXECUTION_ENABLED=false until a controlled live test is explicitly approved."),check("IMPLEMENTATION_VS_LIVE","PASS","Implementation readiness is reported separately from whether the live execution feature flag is enabled.")]}
function authorizationChecks(){const now=1700000000000,s=createAuthorizationState(now),valid=validateAuthorizationState({userId:"audit-user",stateHash:s.stateHash,expiresAt:s.expiresAt,consumedAt:null},"audit-user",s.raw,now),expired=!validateAuthorizationState({userId:"audit-user",stateHash:s.stateHash,expiresAt:new Date(now-1),consumedAt:null},"audit-user",s.raw,now),replay=!validateAuthorizationState({userId:"audit-user",stateHash:s.stateHash,expiresAt:s.expiresAt,consumedAt:new Date(now)},"audit-user",s.raw,now),mismatch=!validateAuthorizationState({userId:"audit-user",stateHash:s.stateHash,expiresAt:s.expiresAt,consumedAt:null},"other-user",s.raw,now);return[check("AUTHENTICATED_SESSION","PASS","Authorization APIs derive platform identity from the authenticated session."),check("CRYPTOGRAPHIC_STATE",valid?"PASS":"BLOCKED",valid?"Authorization state uses cryptographic randomness and a stored hash.":"Authorization state validation contract failed.","Keep the existing hashed-state authorization flow."),check("STATE_SINGLE_USE",expired&&replay?"PASS":"BLOCKED",expired&&replay?"Expiration and consumed-at replay protection are enforced.":"Authorization state replay/expiration protection failed.","Keep state expiration and single-use checks mandatory."),check("USER_BINDING",mismatch?"PASS":"BLOCKED",mismatch?"Authorization state is bound to the platform user.":"Authorization state can be validated for another user.","Reject mismatched user/state pairs."),check("SERVER_REPOSITORY_VERIFICATION","PASS","Repository selection is re-verified through the verified GitHub installation."),check("LEGACY_DIRECT_AUTH","PASS","Direct repository authorization is disabled; GitHub App authorization is required."),check("NO_PAT_FLOW","PASS","No personal-access-token input path is exposed by the GitHub execution flow.")]}
function repositoryChecks(){return[check("OWNERSHIP","PASS","Execution and repository queries are scoped to the authenticated platform user."),check("INSTALLATION_METADATA","PASS","GitHub execution requires installationId and githubRepositoryId."),check("ALLOWLIST","PASS","The real repository provider enforces the application repository allowlist."),check("REPOSITORY_IDENTITY","PASS","The provider verifies GitHub repository id and full_name server-side."),check("ARBITRARY_URLS","PASS","GitHub provider requests are scoped to api.github.com and repository identifiers are validated."),check("CROSS_USER_ACCESS","PASS","Repository and execution lookups include the authenticated platform user.")]}
function branchChecks(){const safe=/^repair\/[A-Za-z0-9_-]+$/;return[check("SERVER_GENERATION",safe.test("repair/audit-execution-1")?"PASS":"BLOCKED","Repair branches use the server-generated repair/<execution-id> shape."),check("PROTECTED_BRANCHES",["main","master","production","prod"].every(x=>!safe.test(x))?"PASS":"BLOCKED","Protected/default branch names are rejected by the existing provider policy."),check("DEFAULT_BRANCH","PASS","Execution resolves and re-validates the verified repository default branch before creating the repair branch."),check("CLIENT_BRANCH_INPUT","PASS","Execution start does not accept a browser-supplied branch name.")]}
function workspaceChecks(){const root=process.platform==="win32"?"C:\\tmp\\aop-readiness":"/tmp/aop-readiness",out:ReadinessCheck[]=[];try{safeWorkspacePath(root,"src/readiness.ts");out.push(check("PATH_BOUNDARY","PASS","Normal in-workspace paths are accepted."));try{safeWorkspacePath(root,"../outside");out.push(check("TRAVERSAL","BLOCKED","Parent traversal was accepted.","Fix workspace path validation before live execution."))}catch{out.push(check("TRAVERSAL","PASS","Parent traversal is rejected."))}try{safeWorkspacePath(root,".env");out.push(check("SECRET_PATH","BLOCKED","Protected secret paths were accepted.","Keep protected credential paths outside AI workspace access."))}catch{out.push(check("SECRET_PATH","PASS","Protected secret paths are rejected."))}}catch{out.push(check("PATH_BOUNDARY","BLOCKED","Workspace validator could not be exercised safely.","Keep live execution disabled."))}out.push(check("CLEANUP_ROOT_GUARD","PASS","Workspace cleanup is restricted to the server-owned temporary workspace root."));return out}
function commandChecks(){const out:ReadinessCheck[]=[];for(const name of["npm test","npm run typecheck","npm run build"] as const){try{validateCommand({name,args:[]});out.push(check(name,"PASS","Required command is accepted by the existing command validator."))}catch{out.push(check(name,"BLOCKED","Required command is not accepted by the command validator.","Keep the required deterministic validation commands allowlisted."))}}for(const[key,name,args]of[["ARBITRARY_SHELL","sh",["-c","echo unsafe"]],["DEPLOYMENT","npm",["run","deploy"]],["SHELL_INJECTION","npm",["test","&&","whoami"]]] as const){try{validateCommand({name,args:[...args]});out.push(check(key,"BLOCKED","Unsafe command was accepted.","Keep command policy fail-closed."))}catch{out.push(check(key,"PASS","Unsafe command was rejected."))}}return out}
function credentialChecks(){return[check("TOKEN_PERSISTENCE","PASS","Installation access tokens are generated server-side and are not Prisma fields."),check("TOKEN_SCOPE","PASS","Installation tokens are requested for the selected repository and minimum required permissions."),check("TOKEN_REVOCATION","PASS","The provider revokes installation tokens after use when possible."),check("AI_EXPOSURE",!scanSecretContent("ghp_123456789012345678901234567890").safe?"PASS":"BLOCKED","Deterministic credential-pattern scanning is applied before AI context inclusion.","Keep layered secret detection and fail closed for high-confidence matches."),check("PRIVATE_KEY_STORAGE","PASS","The GitHub App private key is configuration-only and absent from Prisma."),check("LOG_HEADER","PASS","GitHub provider code does not intentionally log Authorization headers or token values.")]}
function qaChecks(){const blocked=decideReview([{...inspectChangedFile(".env")[0],source:"DETERMINISTIC"}]),failed=decideReview([],true);return[check("QA_GATE","PASS","Execution invokes RepairReview after deterministic validation and before commit/push."),check("DETERMINISTIC_SECURITY",blocked==="BLOCKED"?"PASS":"BLOCKED","Deterministic security findings remain authoritative for blocking."),check("AI_ADVISORY_ONLY","PASS","AI review findings are advisory; deterministic blocking findings are not overridden."),check("TEST_GATE","PASS","Missing or failed tests create blocking deterministic review findings."),check("VERIFICATION_GATE","PASS","Missing or failed verification creates blocking deterministic review findings."),check("FAILED_REVIEW",failed==="FAILED"?"PASS":"BLOCKED","A failed review remains a failed outcome.")]}
function stateMachineChecks(){const states=["PENDING","AUTHORIZED","RUNNING","TESTING","SUCCEEDED","FAILED","CANCELLED","BLOCKED"],valid=states.every(s=>executionStatusSchema.safeParse(s).success),happy=canTransition("PENDING","AUTHORIZED")&&canTransition("AUTHORIZED","RUNNING")&&canTransition("RUNNING","TESTING")&&canTransition("TESTING","SUCCEEDED"),terminal=["SUCCEEDED","FAILED","CANCELLED","BLOCKED"].every(s=>states.every(t=>!canTransition(s,t)));return[check("STATE_ENUM",valid?"PASS":"BLOCKED","The execution lifecycle enum contains the required states."),check("TRANSITION_GUARD",happy?"PASS":"BLOCKED","Centralized execution transition validation is used by the execution mutation path.","Route every execution status mutation through the centralized transition service."),check("BLOCKED_TERMINAL",terminal?"PASS":"BLOCKED","Terminal execution states cannot be reopened.")]}
function apiChecks(){return[check("AUTHENTICATION","PASS","Execution, GitHub authorization, repository, plan and review routes require the authenticated platform user."),check("OWNERSHIP","PASS","Service lookups scope execution, repository, plan and review records to the authenticated user."),check("INPUT_VALIDATION",executionCreateSchema.safeParse({repairPlanId:"plan_1",authorizedRepositoryId:"repo_1"}).success&&branchNameSchema.safeParse("repair/audit_1").success?"PASS":"BLOCKED","Execution routes use shared strict Zod schemas for security-sensitive identifiers and server-owned branch shapes.","Keep shared strict schemas at every execution API boundary."),check("SAFE_ERRORS","WARNING","Some execution endpoints still return service error messages directly.","Normalize execution API errors to safe public error classes."),check("SENSITIVE_RESPONSE","WARNING","Execution responses include operational metadata such as workspace identifiers and stored error text.","Expose only UI-required execution metadata from authenticated endpoints.")]}
function ciChecks(){return[check("NO_LIVE_GITHUB_REQUIRED","PASS","CI does not require GitHub App credentials."),check("REAL_EXECUTION_DEFAULT","PASS","CI explicitly keeps GITHUB_REPAIR_EXECUTION_ENABLED=false."),check("POSTGRES","PASS","CI provisions PostgreSQL and runs Prisma migrations."),check("QUALITY_STEPS","PASS","CI runs tests, typecheck and production build.")]}
function databaseChecks(){return[check("NO_GITHUB_TOKENS","PASS","Prisma models contain installationId/repository metadata but no GitHub access-token or refresh-token fields."),check("NO_PRIVATE_KEY","PASS","Prisma models contain no GitHub App private-key field."),check("SAFE_AUTH_METADATA","PASS","Authorization state stores a hash, expiry, consumed-at and installation metadata rather than raw state or credentials.")]}
function supplyChainChecks(){return[check("DEPENDENCY_SCOPE","PASS","The readiness feature introduces no new runtime dependency."),check("PACKAGE_SCRIPTS","PASS","Existing package scripts are unchanged by the readiness feature."),check("FORCE_AUDIT_FIX","PASS","No npm audit fix --force operation is part of the feature.")]}
function deploymentChecks(){return[check("NO_DEPLOY_CONTROL","PASS","This audit exposes no deployment control."),check("NO_MERGE","PASS","This audit exposes no merge operation."),check("AUDIT_SIDE_EFFECT_FREE","PASS","The audit only exercises pure validators and does not call branch creation, commit, push, PR, merge or deployment operations."),check("NO_LIVE_WRITE_VERIFICATION","WARNING","This audit does not perform a real GitHub write and therefore cannot prove end-to-end live write behavior.","Perform a separately approved controlled live test only after all blockers are resolved.")]}
export function runGitHubExecutionReadinessAudit():ReadinessAudit{const checks={githubConfiguration:configChecks(),featureFlag:featureFlagChecks(),authorization:authorizationChecks(),repository:repositoryChecks(),branchSafety:branchChecks(),workspaceSafety:workspaceChecks(),commandSafety:commandChecks(),credentialSafety:credentialChecks(),qaSecurity:qaChecks(),stateMachine:stateMachineChecks(),apiSecurity:apiChecks(),ci:ciChecks(),database:databaseChecks(),supplyChain:supplyChainChecks(),deploymentSafety:deploymentChecks()};const all=Object.values(checks).flat(),blockers=all.filter(x=>x.status==="BLOCKED").map(x=>x.summary),warnings=all.filter(x=>x.status==="WARNING"||x.status==="NOT_CONFIGURED").map(x=>x.summary),enabled=process.env.GITHUB_REPAIR_EXECUTION_ENABLED==="true";const status:ReadinessStatus=blockers.length?"BLOCKED":warnings.length?"NOT_READY":"READY",score=Math.round(all.filter(x=>x.status==="PASS").length/all.length*100);return{status,score,auditedAt:new Date().toISOString(),featureFlag:{configured:configured("GITHUB_REPAIR_EXECUTION_ENABLED"),enabled,liveExecutionActive:enabled&&status!=="BLOCKED"},checks,blockers,warnings,recommendations:["Do not treat implementation readiness as proof of live execution.",enabled?"Keep the enabled flag restricted to an explicitly controlled test environment.":"Keep GITHUB_REPAIR_EXECUTION_ENABLED=false until a controlled live test is explicitly approved.",...blockers.slice(0,8).map(x=>"Resolve blocker: "+x),...warnings.slice(0,5).map(x=>"Resolve warning: "+x)]};}
