import {z} from "zod";
export const problemCategories=["technical","business","product","customer_support","payments","workflow","productivity","marketing","sales","operations","security","data","infrastructure","other"] as const;
export const problemStatuses=["potential","recurring","high_value"] as const;
export const prospectTypes=["PERSON","ORGANIZATION","TEAM","BUSINESS","UNKNOWN"] as const;
export const qualificationLevels=["LOW","MEDIUM","HIGH","VERY_HIGH"] as const;
export const problemEvidenceSchema=z.object({sourceId:z.string().trim().min(1).max(100).optional(),externalReference:z.string().trim().max(500).optional(),title:z.string().trim().min(1).max(300),summary:z.string().trim().min(1).max(2000),observedAt:z.coerce.date(),sourceType:z.string().trim().min(1).max(100),fingerprint:z.string().trim().min(1).max(200),evidenceConfidence:z.number().int().min(0).max(100).default(70),severity:z.number().int().min(0).max(100).default(50),urgency:z.number().int().min(0).max(100).default(50),solutionFit:z.number().int().min(0).max(100).default(50),businessValueHypothesis:z.number().int().min(0).max(100).default(50),sourceReference:z.string().trim().max(1000).optional()});
export const prospectSchema=z.object({type:z.enum(prospectTypes),displayName:z.string().trim().max(200).optional(),organizationName:z.string().trim().max(200).optional(),publicReference:z.string().url().max(1000).optional(),sourceReference:z.string().trim().max(1000).optional(),roleCategory:z.string().trim().max(200).optional(),confidence:z.number().int().min(0).max(100)});
export function normalizeProblem(text:string){return text.trim().toLowerCase().replace(/[^a-z0-9\s]+/gi," ").replace(/\s+/g," ").trim();}
export function recurrenceScore(i:{evidenceCount:number;sourceDiversity:number;recency:number;severity:number;urgency:number;confidence:number}){return Math.round(Math.min(100,i.evidenceCount*5)*.25+Math.min(100,i.sourceDiversity*20)*.2+i.recency*.15+i.severity*.15+i.urgency*.1+i.confidence*.15);}
export function qualification(i:{severity:number;frequency:number;urgency:number;evidenceStrength:number;solutionFit:number;businessValue:number;recency:number}){const score=Math.round(i.severity*.18+i.frequency*.17+i.urgency*.15+i.evidenceStrength*.17+i.solutionFit*.13+i.businessValue*.1+i.recency*.1);const level=score>=85?"VERY_HIGH":score>=70?"HIGH":score>=50?"MEDIUM":"LOW";return {score,level,reasons:[i.frequency>=70?"recurring problem":null,i.recency>=70?"recent evidence":null,i.severity>=70?"high business impact":null,i.solutionFit>=70?"strong solution fit":null].filter(Boolean) as string[]};}
