import "server-only";
import {createHash} from "node:crypto";
import {getPrisma} from "@/lib/db";
import {problemEvidenceSchema,normalizeProblem,recurrenceScore} from "@/services/problem-discovery-domain";
function fingerprint(value:string){return createHash("sha256").update(normalizeProblem(value)).digest("hex");}
function recency(d:Date){const days=Math.max(0,(Date.now()-d.getTime())/86400000);return Math.max(0,Math.round(100*Math.exp(-days/30)));}
export async function processProblemEvidence(userId:string,input:unknown){const e=problemEvidenceSchema.safeParse(input);if(!e.success)return {status:"rejected" as const,error:"Invalid problem evidence."};const v=e.data;const old=await getPrisma().problemEvidence.findUnique({where:{userId_fingerprint:{userId,fingerprint:v.fingerprint}}});if(old)return {status:"duplicate" as const,problemId:old.problemId};const fp=fingerprint(v.title+" "+v.summary);let problem=await getPrisma().discoveredProblem.findUnique({where:{userId_problemFingerprint:{userId,problemFingerprint:fp}},include:{evidence:true}});if(!problem)problem=await getPrisma().discoveredProblem.create({data:{userId,title:v.title,normalizedProblemStatement:v.summary,problemFingerprint:fp,category:"other",severity:v.severity,evidenceCount:0,sourceDiversity:0,urgency:v.urgency,affectedAudience:"Unknown",affectedMarket:"Unknown",status:"potential",confidence:v.evidenceConfidence,recurringScore:0,recurringExplanation:[]},include:{evidence:true}});const ev=await getPrisma().problemEvidence.create({data:{userId,problemId:problem.id,...v}});const all=[...problem.evidence,ev],diversity=new Set(all.map(x=>x.sourceId??x.sourceType)).size,confidence=Math.round(all.reduce((s,x)=>s+x.evidenceConfidence,0)/all.length),severity=Math.max(...all.map(x=>x.severity)),urgency=Math.max(...all.map(x=>x.urgency)),score=recurrenceScore({evidenceCount:all.length,sourceDiversity:diversity,recency:recency(v.observedAt),severity,urgency,confidence}),status=all.length>=3&&diversity>=2&&score>=70?"high_value":all.length>=2&&diversity>=2?"recurring":"potential";await getPrisma().discoveredProblem.update({where:{id:problem.id},data:{evidenceCount:all.length,sourceDiversity:diversity,severity,urgency,confidence,recurringScore:score,status,recurringExplanation:{evidenceCount:all.length,sourceDiversity:diversity,recency:recency(v.observedAt),severity,urgency,confidence}}});return {status:"saved" as const,problemId:problem.id,recurringScore:score};}
export async function listProblems(userId:string){return getPrisma().discoveredProblem.findMany({where:{userId},include:{evidence:true,prospects:{include:{prospect:true}}},orderBy:{updatedAt:"desc"}});}
export async function getProblem(userId:string,id:string){return getPrisma().discoveredProblem.findFirst({where:{userId,id},include:{evidence:true,prospects:{include:{prospect:true}}}});}
export function evidenceFingerprint(value:string){return fingerprint(value);}
