import {z} from "zod";
export const sourceIntelligenceCategories=["developer_technical","social","messaging_communities","product_reviews","startup_business","web_news","market_other"] as const;
export const sourceIntelligenceTypes=["api","website","community","review","rss","dataset","market_data","other"] as const;
export const signalTypes=["problem_report","user_complaint","product_failure","market_change","business_opportunity","technology_change","startup_signal","trend","other"] as const;
export const problemCategories=["technical","business","product","customer_support","payments","workflow","productivity","marketing","sales","operations","security","data","infrastructure","other"] as const;
export const prospectTypes=["PERSON","ORGANIZATION","TEAM","BUSINESS","UNKNOWN"] as const;
export const prospectDiscoverability=["HIGH","MEDIUM","LOW","NONE"] as const;
export const accessStatuses=["NOT_RESEARCHED","RESEARCHED","OFFICIAL_API_AVAILABLE","LIMITED_ACCESS","PUBLIC_DATA_AVAILABLE","AUTH_REQUIRED","PARTNER_REQUIRED","NOT_RECOMMENDED","NEEDS_VERIFICATION"] as const;
export const priorities=["P0","P1","P2","P3"] as const;
export type Priority=typeof priorities[number];
export type SourceIntelligence={id:string;displayName:string;category:typeof sourceIntelligenceCategories[number];sourceType:typeof sourceIntelligenceTypes[number];description:string;signalTypes:typeof signalTypes[number][];problemCategories:typeof problemCategories[number][];prospectTypes:typeof prospectTypes[number][];prospectDiscoverability:typeof prospectDiscoverability[number];dimensions:{signalQuality:number;recurrencePotential:number;prospectDiscoveryPotential:number;sourceDiversityValue:number;freshness:number;reliability:number;accessFeasibility:number;implementationDifficulty:number;privacyRisk:number;businessValue:number};accessStatus:typeof accessStatuses[number];officialAccessMethod:string;policyConsideration:string;privacyRiskLevel:"LOW"|"MEDIUM"|"HIGH";expectedValue:string;priority:Priority;rationale:string;implementationNotes:string;futureAdapterStatus:"NOT_IMPLEMENTED"|"PLANNED";researchNotes:string[]};
export function calculateSourceValueScore(d:SourceIntelligence["dimensions"]){return Math.max(0,Math.min(100,Math.round(d.signalQuality*.18+d.recurrencePotential*.14+d.prospectDiscoveryPotential*.12+d.sourceDiversityValue*.08+d.freshness*.10+d.reliability*.10+d.accessFeasibility*.10+(100-d.implementationDifficulty)*.08+(100-d.privacyRisk)*.05+d.businessValue*.05)));}
export function priorityForScore(s:number):Priority{s=Number.isFinite(s)?s:0;return s>=80?"P0":s>=65?"P1":s>=50?"P2":"P3";}
export function explainSourceScore(d:SourceIntelligence["dimensions"],score:number){const a=[["signal quality",d.signalQuality],["recurrence potential",d.recurrencePotential],["prospect discovery",d.prospectDiscoveryPotential],["freshness",d.freshness],["reliability",d.reliability],["access feasibility",d.accessFeasibility],["business value",d.businessValue]].sort((x,y)=>Number(y[1])-Number(x[1])).slice(0,3).map(x=>`Strong ${x[0]} (${x[1]}/100).`);const c:string[]=[];if(d.implementationDifficulty>=60)c.push(`Implementation difficulty is ${d.implementationDifficulty}/100.`);if(d.privacyRisk>=40)c.push(`Privacy risk is ${d.privacyRisk}/100 and requires constrained authorized access.`);if(d.accessFeasibility<60)c.push(`Access feasibility is ${d.accessFeasibility}/100 and needs verification or authorization.`);return [...a,...c,score>=80?"Priority is driven by strong expected intelligence value.":"Priority remains below P0 because one or more value/access constraints reduce the score."];}
const R=(id:string,displayName:string,category:any,sourceType:any,description:string,signals:any[],problems:any[],prospects:any[],discover:any,d:any,access:any,method:string,policy:string,privacy:any,expected:string,rationale:string,notes:string[],impl:string):Omit<SourceIntelligence,"priority"|"futureAdapterStatus">=>({id,displayName,category,sourceType,description,signalTypes:signals,problemCategories:problems,prospectTypes:prospects,prospectDiscoverability:discover,dimensions:d,accessStatus:access,officialAccessMethod:method,policyConsideration:policy,privacyRiskLevel:privacy,expectedValue:expected,rationale,implementationNotes:impl,researchNotes:notes});
const D=(signalQuality:number,recurrencePotential:number,prospectDiscoveryPotential:number,sourceDiversityValue:number,freshness:number,reliability:number,accessFeasibility:number,implementationDifficulty:number,privacyRisk:number,businessValue:number)=>({signalQuality,recurrencePotential,prospectDiscoveryPotential,sourceDiversityValue,freshness,reliability,accessFeasibility,implementationDifficulty,privacyRisk,businessValue});
const common=["technical","business","product"] as const;
const raw=[
R("github-issues","GitHub Issues","developer_technical","api","Public issue discussions reveal concrete technical failures, feature gaps and workflow pain.",["problem_report","product_failure","technology_change"],["technical","product","workflow","infrastructure","security","data"],["PERSON","ORGANIZATION","TEAM","BUSINESS"],"HIGH",D(94,91,84,78,88,91,88,28,18,91),"OFFICIAL_API_AVAILABLE","GitHub REST API / GitHub App or authorized token","Use authorized/public repository data and respect GitHub API limits and terms.","LOW","Very high","Strong structured problem reports and mature official access make this an early adapter candidate.",["GitHub documents REST issue endpoints and rate-limit guidance."],"Normalize public issue evidence; do not collect private account data."),
R("stack-overflow","Stack Overflow / Stack Exchange","developer_technical","api","Questions and answers expose recurring developer friction, missing documentation and tooling gaps.",["problem_report","user_complaint","technology_change","trend"],["technical","workflow","productivity","data","infrastructure","security"],["PERSON","TEAM","ORGANIZATION"],"MEDIUM",D(92,89,52,76,84,89,90,25,15,86),"OFFICIAL_API_AVAILABLE","Stack Exchange API","Respect API throttles and caching guidance.","LOW","Very high","High-density technical problem language with mature API access.",["Stack Exchange documents API v2.3 and throttling/caching guidance."],"Prefer public question text and tags; avoid private user fields."),
R("hacker-news","Hacker News","startup_business","api","Startup and technology discussions surface unmet needs, launches, market shifts and repeated complaints.",["startup_signal","business_opportunity","market_change","technology_change","trend"],["business","product","technical","marketing","sales","operations"],["PERSON","ORGANIZATION","TEAM","BUSINESS"],"MEDIUM",D(88,78,65,81,92,86,94,18,12,88),"OFFICIAL_API_AVAILABLE","Official Hacker News Firebase API","Use public data within intended access patterns.","LOW","Very high","Near-real-time public startup and technical discussion with simple official access.",["The official HN API publishes public data in near real time."],"Ingest stories/comments as evidence and retain public references."),
R("rss-news","RSS / News Feeds","web_news","rss","Public feeds reveal market changes, outages, product launches and emerging business problems.",["market_change","technology_change","business_opportunity","trend","problem_report"],["business","product","operations","security","infrastructure","marketing"],["ORGANIZATION","BUSINESS","TEAM","PERSON"],"MEDIUM",D(78,72,58,95,96,74,92,20,10,82),"PUBLIC_DATA_AVAILABLE","Publisher-provided RSS/Atom feeds","Evaluate each publisher's feed terms and attribution requirements.","LOW","High","Excellent source diversity and freshness with low implementation friction.",["Status is feed-by-feed; no blanket API availability is assumed."],"Treat each feed as a distinct source identity."),
R("websites","Public Websites","web_news","website","Public product pages, docs, changelogs and help centers reveal feature gaps and operational pain.",["product_failure","business_opportunity","technology_change","market_change"],["product","customer_support","business","marketing","sales","operations","technical"],["ORGANIZATION","BUSINESS","TEAM"],"HIGH",D(75,68,80,97,78,70,76,48,18,85),"PUBLIC_DATA_AVAILABLE","Publisher-controlled public pages or documented feeds/APIs","Per-site terms, robots rules, access controls and privacy requirements apply.","LOW","High","Broad coverage and strong organization context, but access rules vary by site.",["Access is public-data available, not blanket scraping permission."],"Use domain-specific adapters only for legitimately accessible content."),
R("youtube","YouTube","social","api","Public videos and comments expose product complaints, tutorials and emerging trends.",["user_complaint","product_failure","trend","technology_change"],["product","customer_support","technical","marketing","workflow","productivity"],["PERSON","ORGANIZATION","BUSINESS"],"MEDIUM",D(74,70,66,84,86,82,80,42,22,79),"OFFICIAL_API_AVAILABLE","YouTube Data API","Use official API, quotas and platform policies.","LOW","High","Large public content surface with official access; quota and noise reduce efficiency.",["Google documents API quota usage."],"Prioritize public comments and metadata."),
R("reddit","Reddit","social","community","Community posts and comments reveal candid recurring complaints and workarounds.",["user_complaint","problem_report","trend","business_opportunity"],["product","customer_support","technical","workflow","productivity","business","marketing"],["PERSON","ORGANIZATION","TEAM","BUSINESS"],"MEDIUM",D(86,88,57,87,89,72,54,58,30,88),"LIMITED_ACCESS","Reddit Developer Platform / approved API access","Access rules are changing; follow current developer-platform policies.","MEDIUM","Very high","Exceptional problem language and recurrence, offset by changing access constraints.",["Reddit developer access and privacy rules must be reviewed before adapter work."],"Never assume unrestricted scraping; use approved access only."),
R("product-hunt","Product Hunt","startup_business","api","Product launches and maker discussions reveal new categories, unmet needs and early demand.",["startup_signal","business_opportunity","trend","product_failure"],["product","business","marketing","sales","workflow"],["PERSON","ORGANIZATION","BUSINESS","TEAM"],"HIGH",D(79,65,82,78,87,78,68,42,18,87),"AUTH_REQUIRED","Product Hunt API 2.0 GraphQL","API token required; commercial use requires current terms review.","LOW","High","Strong startup/prospect discovery with explicit API access but commercial-use constraints.",["Product Hunt documents GraphQL API access and commercial-use requirements."],"Preserve public product references and avoid private scopes."),
R("google-play-reviews","Google Play Reviews","product_reviews","review","App reviews expose direct product failures, support pain and repeated requests.",["user_complaint","product_failure","problem_report"],["product","customer_support","payments","technical","workflow","productivity"],["ORGANIZATION","BUSINESS","TEAM"],"MEDIUM",D(91,94,45,70,82,84,58,44,24,91),"AUTH_REQUIRED","Google Play Developer API Reviews","Official review access is tied to authorized publisher/developer access.","LOW","Very high","Excellent recurring app pain signal, constrained by publisher authorization.",["Google documents review resources with review text, ratings and timestamps."],"Target apps the authorized account legitimately manages."),
R("app-store-reviews","Apple App Store Reviews","product_reviews","review","Customer reviews provide strong product, support and usability pain signals for authorized apps.",["user_complaint","product_failure","problem_report"],["product","customer_support","payments","technical","workflow","productivity"],["ORGANIZATION","BUSINESS","TEAM"],"MEDIUM",D(91,94,45,70,80,88,55,46,22,90),"AUTH_REQUIRED","App Store Connect API customerReviews","Access applies to authorized App Store Connect accounts/apps.","LOW","Very high","High-quality recurring product pain with authorization constraints.",["Apple documents customerReviews endpoints and account access requirements."],"Require explicit Apple authorization and app scope."),
R("g2","G2","product_reviews","review","B2B software reviews reveal recurring workflow, support, pricing and product gaps.",["user_complaint","product_failure","business_opportunity","trend"],["business","product","customer_support","workflow","sales","operations"],["ORGANIZATION","BUSINESS","TEAM"],"HIGH",D(87,90,72,73,72,85,50,62,25,92),"OFFICIAL_API_AVAILABLE","G2 API / developer access","Commercial/custom access and current terms must be verified.","LOW","Very high","Excellent B2B pain and organization context; access may require coordination.",["G2 documents programmatic access to product, category and review data."],"Treat API entitlement and commercial terms as prerequisites."),
R("capterra","Capterra","product_reviews","review","B2B software reviews reveal product gaps, support issues and buying criteria.",["user_complaint","product_failure","business_opportunity"],["business","product","customer_support","workflow","sales","operations"],["ORGANIZATION","BUSINESS","TEAM"],"MEDIUM",D(78,82,65,68,64,70,35,72,30,82),"NEEDS_VERIFICATION","Official access method requires verification","Do not assume an open API or scraping permission.","MEDIUM","Medium","Potentially useful B2B pain source but access feasibility is unverified.",["Catalog status intentionally remains needs_verification."],"Keep catalog-only until official access is confirmed."),
R("trustpilot","Trustpilot","product_reviews","review","Consumer reviews reveal support, fulfillment, payment and service failures.",["user_complaint","product_failure","business_opportunity"],["customer_support","payments","operations","product","business","sales"],["ORGANIZATION","BUSINESS"],"HIGH",D(84,91,78,75,78,83,52,55,28,88),"AUTH_REQUIRED","Trustpilot API / Data Solutions / partner programs","Official access programs and entitlement must be verified.","MEDIUM","High","Strong business-level problem signals with program-dependent access.",["Trustpilot documents API authentication and data-access programs."],"Prefer official access and public business references."),
R("telegram-public","Telegram Public Channels","messaging_communities","community","Public communities can expose fast-moving complaints, niche needs and market signals.",["user_complaint","trend","market_change","business_opportunity"],["business","product","marketing","sales","technical","operations"],["PERSON","ORGANIZATION","TEAM","BUSINESS"],"MEDIUM",D(79,83,64,84,94,63,48,65,42,82),"LIMITED_ACCESS","Telegram APIs for legitimately accessible public content","Current Telegram API terms require careful privacy/policy review for AI ingestion.","HIGH","High but policy-sensitive","Fast niche signals are valuable but current policy constraints are significant.",["Telegram API terms must be checked against the exact AI ingestion use case."],"Keep research-only until policy compatibility is confirmed."),
R("discord-public","Discord Public Communities","messaging_communities","community","Authorized communities reveal live product feedback, support pain and demand.",["user_complaint","product_failure","trend","business_opportunity"],["product","customer_support","technical","workflow","business"],["PERSON","ORGANIZATION","TEAM","BUSINESS"],"MEDIUM",D(82,86,60,83,96,70,45,70,50,84),"LIMITED_ACCESS","Discord Apps/Bots with server-granted permissions","Server permissions and privileged message-content access are controlled.","HIGH","High but access-sensitive","Excellent live community signal, but access is permissioned.",["Discord documentation governs privileged intents and message-content access."],"Require explicit server authorization and minimum necessary permissions."),
R("x-twitter","X / Twitter","social","api","Public posts can reveal breaking complaints, product feedback and market reactions.",["user_complaint","market_change","trend","technology_change"],["product","marketing","customer_support","business","sales","technical"],["PERSON","ORGANIZATION","BUSINESS"],"HIGH",D(83,78,83,90,99,55,32,78,36,90),"NEEDS_VERIFICATION","Official X API access path must be verified for the intended plan/tier","Pricing, quotas and commercial terms can change; do not assume unrestricted access.","MEDIUM","High but uncertain","Exceptional freshness and reach, but current access feasibility is too uncertain for P0.",["Current X API tier and terms require verification before adapter work."],"Research current official access before implementation."),
R("public-forums","Public Forums","web_news","community","Niche forums contain detailed recurring workflow and product problems.",["problem_report","user_complaint","trend"],["technical","product","workflow","productivity","operations","customer_support","business"],["PERSON","ORGANIZATION","TEAM","BUSINESS"],"MEDIUM",D(80,85,55,88,70,62,58,65,34,79),"PUBLIC_DATA_AVAILABLE","Forum-provided APIs, RSS, exports or other authorized public access","Each forum has its own terms and privacy rules.","MEDIUM","High","Strong niche problem depth but heterogeneous access makes adapters domain-specific.",["Catalog represents a source class, not a universal API."],"Build adapters per forum only after confirming legitimate access."),
R("market-data","Public Market Data","market_other","market_data","Public market datasets contextualize demand, pricing, industry changes and adoption.",["market_change","trend","business_opportunity"],["business","sales","marketing","operations","data"],["ORGANIZATION","BUSINESS"],"LOW",D(72,76,32,90,92,88,72,40,10,84),"PUBLIC_DATA_AVAILABLE","Dataset/provider-specific public or licensed APIs","Terms and redistribution rights vary by provider.","LOW","High as context","Useful corroborating evidence and trend confirmation, but weaker direct problem language.",["Provider-specific access and redistribution rights must be verified."],"Use as corroborating evidence rather than primary complaint discovery.")
];
export const sourceIntelligenceCatalog:SourceIntelligence[]=raw.map(x=>{const s=calculateSourceValueScore(x.dimensions);return {...x,priority:priorityForScore(s),futureAdapterStatus:"NOT_IMPLEMENTED" as const};});
export const sourceIntelligenceReviewSchema=z.object({rationale:z.string().trim().max(2000).optional(),priority:z.enum(priorities).optional(),accessStatus:z.enum(accessStatuses).optional(),implementationNotes:z.string().trim().max(3000).optional()}).strict();
export function getSourceIntelligence(id:string){return sourceIntelligenceCatalog.find(x=>x.id===id)??null;}
export function listSourceIntelligence(f:{priority?:string;category?:string;problemCategory?:string;prospectPotential?:string;sort?:string}={}){let a=[...sourceIntelligenceCatalog];if(f.priority)a=a.filter(x=>x.priority===f.priority);if(f.category)a=a.filter(x=>x.category===f.category);if(f.problemCategory)a=a.filter(x=>x.problemCategories.includes(f.problemCategory as never));if(f.prospectPotential)a=a.filter(x=>x.prospectDiscoverability===f.prospectPotential);const score=(x:SourceIntelligence)=>calculateSourceValueScore(x.dimensions);a.sort((x,y)=>f.sort==="name"?x.displayName.localeCompare(y.displayName):score(y)-score(x));return a.map(x=>({...x,valueScore:score(x),scoreExplanation:explainSourceScore(x.dimensions,score(x))}));}
