import "server-only";
import { z } from "zod";
export const STACKEXCHANGE_API_HOST="api.stackexchange.com";
const BASE="https://api.stackexchange.com/2.3";
const sitePattern=/^[a-z0-9][a-z0-9-]{1,49}$/;
export const stackExchangeConfigSchema=z.object({site:z.string().trim().regex(sitePattern),tags:z.array(z.string().trim().regex(/^[a-z0-9][a-z0-9+.#-]{0,49}$/i)).max(5).default([]),sort:z.enum(["activity","creation","votes","hot","week","month"]).default("activity"),order:z.enum(["asc","desc"]).default("desc"),limit:z.number().int().min(1).max(100).default(20),lookback:z.number().int().min(1).max(720).default(24),intitle:z.string().trim().min(1).max(120).optional()}).strict();
export type StackExchangeConfig=z.infer<typeof stackExchangeConfigSchema>;
export type StackExchangeQuestion={question_id:number;title:string;body?:string;link:string;tags?:string[];score?:number;answer_count?:number;view_count?:number;creation_date:number;last_activity_date:number;is_answered?:boolean;accepted_answer_id?:number;closed_date?:number;closed_reason?:string;owner?:{display_name?:string;user_id?:number;user_type?:string}};
type Wrapper={items?:unknown[];quota_remaining?:number;quota_max?:number;backoff?:number;error_id?:number;error_message?:string;error_name?:string};
export type NormalizedStackExchangeQuestion={externalId:string;site:string;questionId:number;title:string;summary:string;bodyExcerpt:string;tags:string[];reference:string;score:number;answerCount:number;viewCount:number;createdAt:Date;lastActivityAt:Date;isAnswered:boolean;acceptedAnswerId?:number;closedDate?:Date;closedReason?:string;authorDisplayName?:string;category:string;severity:number;urgency:number;signalType:string};
function stripHtml(v:string){return v.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();}
function endpoint(c:StackExchangeConfig){const q=new URLSearchParams({site:c.site,pagesize:String(c.limit),sort:c.sort,order:c.order,filter:"withbody"});if(c.tags.length)q.set("tagged",c.tags.join(";"));if(c.intitle)q.set("intitle",c.intitle);q.set("fromdate",String(Math.floor((Date.now()-c.lookback*3600000)/1000)));return BASE+"/questions?"+q.toString();}
async function request(url:string,timeoutMs=8000){if(!url.startsWith("https://"+STACKEXCHANGE_API_HOST+"/2.3/"))return{ok:false as const,error:"Unsafe Stack Exchange API host."};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const res=await fetch(url,{headers:{Accept:"application/json"},signal:controller.signal,cache:"no-store"});let data:unknown;try{data=await res.json();}catch{return{ok:false as const,error:"Stack Exchange returned malformed JSON.",status:res.status};}const w=data&&typeof data==="object"?data as Wrapper:{};if(w.backoff)return{ok:false as const,error:"Stack Exchange requested backoff: "+w.backoff+"s.",status:429,retryAfter:w.backoff};if(w.error_id)return{ok:false as const,error:"Stack Exchange API returned an application error.",status:res.status};if(!res.ok)return{ok:false as const,error:res.status===429?"Stack Exchange API rate limit reached.":"Stack Exchange API request failed (HTTP "+res.status+").",status:res.status};if(typeof w.quota_remaining==="number"&&w.quota_remaining<=0)return{ok:false as const,error:"Stack Exchange API quota exhausted.",status:429};return{ok:true as const,status:res.status,data:w};}catch(e){return{ok:false as const,error:e instanceof Error&&e.name==="AbortError"?"Stack Exchange API request timed out.":"Unable to reach Stack Exchange API.",status:0};}finally{clearTimeout(timer);}}
export function validateStackExchangeConfig(input:unknown){return stackExchangeConfigSchema.safeParse(input);}
export function classifyStackExchangeQuestion(q:Pick<NormalizedStackExchangeQuestion,"title"|"summary"|"tags">){const text=(q.title+" "+q.summary+" "+q.tags.join(" ")).toLowerCase();if(/cve|vulnerab|exploit|csrf|xss|injection|authorization flaw|security flaw|secret leak/.test(text))return{category:"security",severity:90,urgency:88,signalType:"product_failure"};if(/stripe|paypal|payment|billing|invoice|checkout|refund|subscription/.test(text))return{category:"payments",severity:82,urgency:80,signalType:"user_complaint"};if(/docker|kubernetes|deploy|deployment|nginx|server config|networking|cloud|aws|azure|gcp|container/.test(text))return{category:"infrastructure",severity:80,urgency:76,signalType:"product_failure"};if(/sql|database|postgres|mysql|mongodb|query|dataframe|pandas|data corruption|etl/.test(text))return{category:"data",severity:78,urgency:72,signalType:"product_failure"};if(/workflow|automation|repetitive|developer experience|productivity|tooling friction/.test(text))return{category:text.includes("productivity")?"productivity":"workflow",severity:68,urgency:60,signalType:"problem_report"};if(/feature request|missing feature|doesn't support|does not support|limitation|capability gap/.test(text))return{category:"product",severity:62,urgency:55,signalType:"problem_report"};if(/support|customer service|account help|user support/.test(text))return{category:"customer_support",severity:60,urgency:58,signalType:"user_complaint"};if(/marketing|seo/.test(text))return{category:"marketing",severity:58,urgency:52,signalType:"problem_report"};if(/sales|crm|lead generation/.test(text))return{category:"sales",severity:60,urgency:55,signalType:"problem_report"};if(/operations|business process/.test(text))return{category:"operations",severity:60,urgency:55,signalType:"problem_report"};if(/bug|error|exception|crash|timeout|failed|failure|not working|cannot|can't/.test(text))return{category:"technical",severity:76,urgency:70,signalType:"product_failure"};return{category:"other",severity:55,urgency:50,signalType:"problem_report"};}
export function normalizeStackExchangeQuestion(q:StackExchangeQuestion,c:StackExchangeConfig):NormalizedStackExchangeQuestion|null{if(!Number.isInteger(q.question_id)||q.question_id<1||!q.title||!q.link||!Number.isFinite(q.creation_date)||!Number.isFinite(q.last_activity_date))return null;const bodyExcerpt=stripHtml(q.body??"").slice(0,2000),summary=(bodyExcerpt||q.title).slice(0,2000),cls=classifyStackExchangeQuestion({title:q.title,summary,tags:q.tags??[]});return{externalId:c.site+"/"+q.question_id,site:c.site,questionId:q.question_id,title:q.title.trim(),summary,bodyExcerpt,tags:(q.tags??[]).slice(0,20),reference:q.link,score:q.score??0,answerCount:q.answer_count??0,viewCount:q.view_count??0,createdAt:new Date(q.creation_date*1000),lastActivityAt:new Date(q.last_activity_date*1000),isAnswered:q.is_answered===true,acceptedAnswerId:q.accepted_answer_id,closedDate:q.closed_date?new Date(q.closed_date*1000):undefined,closedReason:q.closed_reason,authorDisplayName:q.owner?.display_name,...cls};}
export async function fetchStackExchangeQuestions(config:StackExchangeConfig){const parsed=stackExchangeConfigSchema.safeParse(config);if(!parsed.success)return{ok:false as const,error:"Invalid Stack Exchange configuration."};const r=await request(endpoint(parsed.data));if(!r.ok)return{ok:false as const,error:r.error,status:r.status,retryAfter:r.retryAfter};if(!Array.isArray(r.data.items))return{ok:false as const,error:"Stack Exchange returned an unexpected response.",status:r.status};const questions=r.data.items.filter((x):x is StackExchangeQuestion=>!!x&&typeof x==="object").map(x=>normalizeStackExchangeQuestion(x,parsed.data)).filter((x):x is NormalizedStackExchangeQuestion=>!!x).slice(0,parsed.data.limit);return{ok:true as const,questions,rawCount:r.data.items.length,quotaRemaining:r.data.quota_remaining??null};}
export async function stackExchangeHealthCheck(config:unknown){const parsed=stackExchangeConfigSchema.safeParse(config);if(!parsed.success)return{ok:false as const,error:"Invalid Stack Exchange configuration."};const r=await request(BASE+"/questions?site="+encodeURIComponent(parsed.data.site)+"&pagesize=1&sort=activity&order=desc&filter=default");return r.ok?{ok:true as const,quotaRemaining:r.data.quota_remaining??null}:{ok:false as const,error:r.error,status:r.status,retryAfter:r.retryAfter};}
export function stackExchangeEndpointForTest(config:StackExchangeConfig){return endpoint(config);}
