"use client";
import {useEffect,useState} from "react";
type Signal={id:string;title:string;summary:string;signalType:string;sourceName:string;receivedAt:string;confidence:number;opportunityAnalysisStatus:string};
export function IntelligencePanel(){const [signals,setSignals]=useState<Signal[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/intelligence/signals/recent");const d=await r.json();if(r.ok)setSignals(d.signals);else setMessage(d.error||"Unable to load signals.");setLoading(false)}
 useEffect(()=>{load()},[]);
 async function ingest(){setMessage("");const r=await fetch("/api/intelligence/signals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"mock"})});const d=await r.json();if(!r.ok){setMessage(d.error||"Unable to ingest.");return}setMessage("Mock signals processed.");await load()}
 async function analyze(id:string){setBusy(id);setMessage("");const r=await fetch("/api/intelligence/signals/"+id+"/opportunity",{method:"POST"});const d=await r.json();setBusy(null);if(!r.ok){setMessage(d.error||"Analysis failed.");return}setMessage("Opportunity assessment created.");await load()}
 return <section><div className="actions"><button className="button" onClick={ingest}>Load mock signals</button></div>{message&&<p className="muted">{message}</p>}{loading?<p>Loading…</p>:signals.length===0?<p>No signals yet.</p>:signals.map(s=><article className="card" key={s.id}><p className="eyebrow">{s.signalType} · {s.sourceName}</p><h2>{s.title}</h2><p>{s.summary}</p><p className="muted">{new Date(s.receivedAt).toLocaleString()} · confidence {s.confidence}%</p>{s.opportunityAnalysisStatus==="analyzed"?<p>Opportunity analysis completed.</p>:<button className="button" disabled={busy===s.id} onClick={()=>analyze(s.id)}>{busy===s.id?"Analyzing…":"Analyze opportunity"}</button>}</article>)}</section>}
